### ISSUE TITLE
Force enable in task scheduler

### ISSUE THREAD

**Issue by anthr76** [Nonary/AutoHDRSwitch#5]
Hello! I would like to enable HDR with task scheduler via this script but nothing seems to happen if I invoke `onStreamEnd` function. 

Reason being is sometimes I shutdown the sunshine host via moonlight which doesn't give sunshine a chance to do post down scripts.

Is there a way to unconditionally enable HDR via powershell?

**Comment by Nonary** [comment]
You have to "dot source" the file first in PowerShell in order to call the function. Here's an example that you can set as the command to fire on the task scheduler.

`powershell.exe -executionpolicy bypass -windowstyle hidden -Command "& { . 'F:\sources\AutoHDRSwitch\HDRSwitch-Functions.ps1'; OnStreamEnd }"`

Change the path above to match the location of your script, should work.

If you're just wanting to always have HDR enabled, instead of calling OnStreamEnd you can use [HDRController]::EnableGlobalHDRState()
